# Generated by Django 3.2.6 on 2021-09-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='patient_address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobileno',
            new_name='patient_mobileno',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='patient_name',
        ),
    ]
