# Generated by Django 3.2.6 on 2021-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210918_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=70)),
                ('brand_name', models.CharField(max_length=70)),
                ('medicine_quantity', models.IntegerField()),
                ('medicine_price', models.IntegerField()),
            ],
        ),
    ]
