# Generated by Django 3.2.6 on 2021-09-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='brand_name',
            new_name='brandname',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='medicinename',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_price',
            new_name='medicineprice',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_quantity',
            new_name='medicinequantity',
        ),
    ]
