# Generated by Django 3.2.6 on 2021-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210928_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='medicineprice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='medicinetiming',
            field=models.CharField(max_length=100),
        ),
    ]
