# Generated by Django 3.2.6 on 2021-09-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_receipt2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receipt2',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='medicineprice',
        ),
    ]
