# Generated by Django 3.2.6 on 2021-10-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_receipt_medicineprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicineoutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ousidemedicinename', models.CharField(max_length=20)),
                ('ousidemedicineprice', models.CharField(max_length=20)),
            ],
        ),
    ]
