# Generated by Django 3.2.8 on 2021-10-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_ousidemedicineprice_medicineoutside_ousidemedicinetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicineoutsideHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ousidemedicinename', models.CharField(max_length=20)),
                ('ousidemedicinetime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='receiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('medicinename', models.CharField(max_length=70)),
                ('medicinetiming', models.CharField(max_length=100)),
                ('medicineprice', models.CharField(default='HELLO', max_length=100)),
            ],
        ),
    ]
