# Generated by Django 3.2.8 on 2021-10-17 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_medicineoutsidehistory_receipthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineoutside',
            name='username',
            field=models.CharField(default='no user', max_length=30),
        ),
        migrations.AddField(
            model_name='medicineoutsidehistory',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineoutsidehistory',
            name='username',
            field=models.CharField(default='no user', max_length=30),
        ),
    ]
