# Generated by Django 3.2.8 on 2021-10-17 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211017_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipthistory',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
