# Generated by Django 3.2.6 on 2021-10-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_receipthistory_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='bdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraganizers', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('st', models.DateField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
