# Generated by Django 3.2.6 on 2021-10-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bdc_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('mobileno', models.IntegerField()),
                ('bloodgroup', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=10)),
                ('healthissue', models.CharField(max_length=100)),
            ],
        ),
    ]
