# Generated by Django 3.2.6 on 2021-10-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blooddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bdc',
        ),
    ]
