# Generated by Django 3.2.6 on 2021-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_bdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('hospitaname', models.CharField(max_length=100)),
            ],
        ),
    ]
