# Generated by Django 3.2.6 on 2021-11-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_doctorsetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctorsetails',
            new_name='doctorsdetails',
        ),
    ]
