# Generated by Django 3.2.6 on 2021-11-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_doctorsetails_doctorsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdetails',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
