# Generated by Django 3.2.6 on 2021-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_patient_patient_mobileno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='patient_firstname',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_lastname',
            field=models.CharField(default='HELLO', max_length=70),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_middlename',
            field=models.CharField(default='HELLO', max_length=70),
        ),
    ]
