# Generated by Django 3.2.6 on 2021-11-11 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
