# Generated by Django 3.2.6 on 2021-11-11 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_patient_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
