# Generated by Django 3.2.6 on 2021-11-11 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_medicine_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='patientname',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='patient_firstname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='patient_lastname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='patient_middlename',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
