# Generated by Django 3.2.6 on 2021-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_notes_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='criticalpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_firstname', models.CharField(max_length=70)),
                ('patient_middlename', models.CharField(default='', max_length=70)),
                ('patient_lastname', models.CharField(default='', max_length=70)),
                ('patient_address', models.CharField(max_length=70)),
                ('patient_mobileno', models.IntegerField()),
                ('prescribedoctorname', models.CharField(max_length=70)),
                ('healthproblem', models.CharField(max_length=70)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
