# Generated by Django 3.2.6 on 2021-11-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_criticalpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='healthproblem',
            new_name='chealthproblem',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='patient_address',
            new_name='cpatient_address',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='patient_firstname',
            new_name='cpatient_firstname',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='patient_lastname',
            new_name='cpatient_lastname',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='patient_middlename',
            new_name='cpatient_middlename',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='patient_mobileno',
            new_name='cpatient_mobileno',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='prescribedoctorname',
            new_name='cprescribedoctorname',
        ),
        migrations.RenameField(
            model_name='criticalpatient',
            old_name='time',
            new_name='ctime',
        ),
    ]
