# Generated by Django 3.2.6 on 2021-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211112_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipthistory',
            name='medicineprice',
            field=models.IntegerField(),
        ),
    ]
