# Generated by Django 3.2.6 on 2021-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_receipthistory_medicineprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='medicineprice',
            field=models.IntegerField(),
        ),
    ]
