# Generated by Django 3.2.6 on 2021-11-12 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_receipt_medicineprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_mobileno',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
