# Generated by Django 3.2.6 on 2021-11-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_patient_patient_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_mobileno',
            field=models.IntegerField(),
        ),
    ]
