# Generated by Django 3.2.6 on 2021-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_patient_patient_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=10, null=True),
        ),
    ]
