# Generated by Django 3.2.6 on 2021-11-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20211113_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='healthissue',
        ),
    ]
